name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: jerrymbola/jm-portfolio-source
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js (Optional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies (If applicable)
        run: |
          npm install  # If using a build step like React/Vite

      - name: Build Project (Modify as Needed)
        run: |
          npm run build  # Change this if needed
          cp -r dist/* ../public-repo  # Adjust if output folder is different

      - name: Push to Public Repo
        run: |
          cd ../public-repo
          git init
          git remote add origin https://github.com/jerrymbola/jerrymbola.github.io.git
          git checkout -b main
          git add .
          git commit -m "Deploy updated portfolio"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
