name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: jerrymbola/jm-portfolio-source
          token: ${{ secrets.GH_PAT }}

      - name: Push to Public Repo
        run: |
          git clone https://github.com/jerrymbola/jerrymbola.github.io.git ../public-repo
          rsync -av --delete . ../public-repo
          cd ../public-repo
          git add .
          git commit -m "Deploy updated portfolio" || echo "No changes to commit"
          git push origin main
